//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiLi_Library.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public int BookInfoID { get; set; }
        public int BooklD { get; set; }
        public int SectionOrder { get; set; }
        public string SectionContent { get; set; }
        public Nullable<int> SubSectionOrder { get; set; }
        public string SubSectionContent { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte BookListType { get; set; }
        public string Remark { get; set; }
    }
}
